### ISSUE TITLE
Error when running md simulation for intrinsically disordered protein

### ISSUE THREAD

**Issue by doppler12effect** [KULL-Centre/_2024_Cao_CALVADOSCOM#3]
Hello! I followed the Run single-chain simulations with CALVADOS 3 in README for intrinsically disordered protein then get this error after running submit_ray.py

Traceback (most recent call last):
  File "/home/petlada/miniconda3/envs/CALVADOS3/lib/python3.8/site-packages/MDAnalysis/coordinates/base.py", line 1512, in __del__
    self.close()
  File "/home/petlada/miniconda3/envs/CALVADOS3/lib/python3.8/site-packages/MDAnalysis/coordinates/DCD.py", line 181, in close
    self._file.close()
AttributeError: 'DCDReader' object has no attribute '_file'
Traceback (most recent call last):
  File "submit_ray.py", line 216, in <module>
    proc = subprocess.run(['sbatch', f"{cwd}/{dataset}/{record}/{cycle}/{record}_sim{replicas_list4MD_idx}.sh"],capture_output=True)
  File "/home/petlada/miniconda3/envs/CALVADOS3/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/petlada/miniconda3/envs/CALVADOS3/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/petlada/miniconda3/envs/CALVADOS3/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sbatch'

What should I do?

**Comment by fancaoErik** [comment]
Hi there! Your server seems not to support using `sbatch` to submit computing jobs. Please go for this script instead https://github.com/KULL-Centre/_2024_Cao_CALVADOSCOM/blob/main/src/simple_singlechain.py, which does not require any HPC configuration.

Hope this could help you.
Fan

**Comment by fancaoErik** [comment]
I am closing this one if the problem has already been solved.
